<script src="../assets/js/jquery-3.3.1.min.js"></script>
<script src="../assets/js/owl.carousel.js"></script>
<script src="../assets/js/popper.min.js"></script>
<script src="../assets/js/tippy-bundle.iife.min.js"></script>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/switchery.js"></script>
<script src="../assets/js/easytimer.min.js">        </script>
<script src="../assets/js/index.js">        </script>
<script src="../assets/js/feather-icon/feather.min.js"></script>
<script src="../assets/js/feather-icon/feather-icon.js"></script>
<script src="../assets/js/ckeditor/ckeditor.js"></script>
<script src="../assets/js/ckeditor/styles.js"></script>
<script src="../assets/js/ckeditor/adapters/jquery.js"></script>
<script src="../assets/js/ckeditor/ckeditor.custom.js"></script>
<script src="../assets/js/date-picker/datepicker.js"></script>
<script src="../assets/js/date-picker/datepicker.en.js"></script>
<script src="../assets/js/date-picker/datepicker.custom.js"></script>
<!-- <script src="../assets/js/tour/intro.js"></script>
<script src="../assets/js/tour/intro-init.js"></script> -->
<script src="../assets/js/jquery.magnific-popup.js"></script>
<script src="../assets/js/zoom-gallery.js"></script>
<script src="../assets/js/script.js"></script>